Algoritmo "EntradaProcessamentoSaida"

Var
num1: real
num2: real
resultado: real

Inicio
Escreval("Entrada, Processamento e Saída")
Escreval("Digite o primeiro número: ")
Leia(num1)
Escreval("Digite o segundo número: ")
Leia(num2)

resultado <- num1*num2

Escreval("Os números são: ")
Escreval("Primeiro número digitado: ", num1)
Escreval("Segundo número digitado: ", num2)
Escreval("Resultado: ", resultado)

Fimalgoritmo