Algoritmo "VetorNotasDe5Alunxs"

Var
notas: vetor [1..5] de real
contadorLoop1: inteiro
media: real
soma: real

Inicio
Para contadorLoop1 de 1 ate 5 faca
     Escreva("Digite a nota dx alunx número ", contadorLoop1, " de 5: ")
     Leia(notas[contadorLoop1])
     soma <- soma + notas[contadorLoop1]
FimPara

Para contadorLoop1 de 1 ate 5 faca
     Escreval("Nota dx alunx ", notas[contadorLoop1])
FimPara

Fimalgoritmo
